# Generated by Django 4.2.6 on 2023-10-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_webstories_editor', '0010_webstoriespublisherlogo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webstoriespublisherlogo',
            name='slug',
        ),
        migrations.AddField(
            model_name='webstory',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
